// Auto-generated from structural-formula-registry.json
// dev-tools用: カテゴリ・名称の簡易マップ

export const COMPOUND_META: Record<string, { name_ja: string; name_en: string; category: string }> = {
  "struct-purine": { name_ja: "プリン環", name_en: "Purine", category: "heterocycle" },
  "struct-pyrimidine": { name_ja: "ピリミジン環", name_en: "Pyrimidine", category: "heterocycle" },
  "struct-indole": { name_ja: "インドール環", name_en: "Indole", category: "heterocycle" },
  "struct-quinoline": { name_ja: "キノリン環", name_en: "Quinoline", category: "heterocycle" },
  "struct-imidazole": { name_ja: "イミダゾール環", name_en: "Imidazole", category: "heterocycle" },
  "struct-thiazole": { name_ja: "チアゾール環", name_en: "Thiazole", category: "heterocycle" },
  "struct-pyridine": { name_ja: "ピリジン環", name_en: "Pyridine", category: "heterocycle" },
  "struct-pyrrole": { name_ja: "ピロール環", name_en: "Pyrrole", category: "heterocycle" },
  "struct-furan": { name_ja: "フラン環", name_en: "Furan", category: "heterocycle" },
  "struct-thiophene": { name_ja: "チオフェン環", name_en: "Thiophene", category: "heterocycle" },
  "struct-benzodiazepine": { name_ja: "ベンゾジアゼピン環", name_en: "Benzodiazepine", category: "heterocycle" },
  "struct-phenothiazine": { name_ja: "フェノチアジン環", name_en: "Phenothiazine", category: "heterocycle" },
  "struct-steroid": { name_ja: "ステロイド骨格", name_en: "Steroid", category: "heterocycle" },
  "struct-beta-lactam": { name_ja: "β-ラクタム環", name_en: "Beta-Lactam", category: "heterocycle" },
  "struct-adenine": { name_ja: "アデニン", name_en: "Adenine", category: "heterocycle" },
  "struct-guanine": { name_ja: "グアニン", name_en: "Guanine", category: "heterocycle" },
  "struct-caffeine": { name_ja: "カフェイン", name_en: "Caffeine", category: "heterocycle" },
  "struct-hypoxanthine": { name_ja: "ヒポキサンチン", name_en: "Hypoxanthine", category: "heterocycle" },
  "struct-uric-acid": { name_ja: "尿酸", name_en: "Uric acid", category: "heterocycle" },
  "struct-cytosine": { name_ja: "シトシン", name_en: "Cytosine", category: "heterocycle" },
  "struct-uracil": { name_ja: "ウラシル", name_en: "Uracil", category: "heterocycle" },
  "struct-thymine": { name_ja: "チミン", name_en: "Thymine", category: "heterocycle" },
  "struct-serotonin": { name_ja: "セロトニン", name_en: "Serotonin", category: "heterocycle" },
  "struct-tryptophan": { name_ja: "トリプトファン", name_en: "Tryptophan", category: "heterocycle" },
  "struct-quinine": { name_ja: "キニーネ", name_en: "Quinine", category: "heterocycle" },
  "struct-histamine": { name_ja: "ヒスタミン", name_en: "Histamine", category: "heterocycle" },
  "struct-histidine": { name_ja: "ヒスチジン", name_en: "Histidine", category: "heterocycle" },
  "struct-furosemide": { name_ja: "フロセミド", name_en: "Furosemide", category: "heterocycle" },
  "struct-ticlopidine": { name_ja: "チクロピジン", name_en: "Ticlopidine", category: "heterocycle" },
  "struct-diazepam": { name_ja: "ジアゼパム", name_en: "Diazepam", category: "heterocycle" },
  "struct-midazolam": { name_ja: "ミダゾラム", name_en: "Midazolam", category: "heterocycle" },
  "struct-chlorpromazine": { name_ja: "クロルプロマジン", name_en: "Chlorpromazine", category: "heterocycle" },
  "struct-cholesterol": { name_ja: "コレステロール", name_en: "Cholesterol", category: "heterocycle" },
  "struct-prednisolone": { name_ja: "プレドニゾロン", name_en: "Prednisolone", category: "heterocycle" },
  "struct-penicillin-g": { name_ja: "ペニシリンG", name_en: "Penicillin G", category: "heterocycle" },
  "struct-cephalothin": { name_ja: "セファロチン", name_en: "Cephalothin", category: "heterocycle" },
  "struct-tetracycline": { name_ja: "テトラサイクリン", name_en: "Tetracycline", category: "heterocycle" },
  "struct-retinol": { name_ja: "レチノール(ビタミンA)", name_en: "Retinol", category: "vitamin" },
  "struct-thiamine": { name_ja: "チアミン(ビタミンB1)", name_en: "Thiamine", category: "vitamin" },
  "struct-riboflavin": { name_ja: "リボフラビン(ビタミンB2)", name_en: "Riboflavin", category: "vitamin" },
  "struct-niacin": { name_ja: "ナイアシン(ビタミンB3)", name_en: "Niacin", category: "vitamin" },
  "struct-pantothenic-acid": { name_ja: "パントテン酸(ビタミンB5)", name_en: "Pantothenic acid", category: "vitamin" },
  "struct-pyridoxine": { name_ja: "ピリドキシン(ビタミンB6)", name_en: "Pyridoxine", category: "vitamin" },
  "struct-biotin": { name_ja: "ビオチン(ビタミンB7)", name_en: "Biotin", category: "vitamin" },
  "struct-folic-acid": { name_ja: "葉酸(ビタミンB9)", name_en: "Folic acid", category: "vitamin" },
  "struct-cyanocobalamin": { name_ja: "シアノコバラミン(ビタミンB12)", name_en: "Cyanocobalamin", category: "vitamin" },
  "struct-ascorbic-acid": { name_ja: "アスコルビン酸(ビタミンC)", name_en: "Ascorbic acid", category: "vitamin" },
  "struct-cholecalciferol": { name_ja: "コレカルシフェロール(ビタミンD3)", name_en: "Cholecalciferol", category: "vitamin" },
  "struct-alpha-tocopherol": { name_ja: "α-トコフェロール(ビタミンE)", name_en: "alpha-Tocopherol", category: "vitamin" },
  "struct-phylloquinone": { name_ja: "フィロキノン(ビタミンK1)", name_en: "Phylloquinone", category: "vitamin" },
  "struct-glycine": { name_ja: "グリシン", name_en: "Glycine", category: "amino_acid" },
  "struct-alanine": { name_ja: "アラニン", name_en: "Alanine", category: "amino_acid" },
  "struct-valine": { name_ja: "バリン", name_en: "Valine", category: "amino_acid" },
  "struct-leucine": { name_ja: "ロイシン", name_en: "Leucine", category: "amino_acid" },
  "struct-isoleucine": { name_ja: "イソロイシン", name_en: "Isoleucine", category: "amino_acid" },
  "struct-proline": { name_ja: "プロリン", name_en: "Proline", category: "amino_acid" },
  "struct-phenylalanine": { name_ja: "フェニルアラニン", name_en: "Phenylalanine", category: "amino_acid" },
  "struct-methionine": { name_ja: "メチオニン", name_en: "Methionine", category: "amino_acid" },
  "struct-serine": { name_ja: "セリン", name_en: "Serine", category: "amino_acid" },
  "struct-threonine": { name_ja: "トレオニン", name_en: "Threonine", category: "amino_acid" },
  "struct-cysteine": { name_ja: "システイン", name_en: "Cysteine", category: "amino_acid" },
  "struct-tyrosine": { name_ja: "チロシン", name_en: "Tyrosine", category: "amino_acid" },
  "struct-asparagine": { name_ja: "アスパラギン", name_en: "Asparagine", category: "amino_acid" },
  "struct-glutamine": { name_ja: "グルタミン", name_en: "Glutamine", category: "amino_acid" },
  "struct-aspartic-acid": { name_ja: "アスパラギン酸", name_en: "Aspartic acid", category: "amino_acid" },
  "struct-glutamic-acid": { name_ja: "グルタミン酸", name_en: "Glutamic acid", category: "amino_acid" },
  "struct-lysine": { name_ja: "リシン", name_en: "Lysine", category: "amino_acid" },
  "struct-arginine": { name_ja: "アルギニン", name_en: "Arginine", category: "amino_acid" },
  "struct-lansoprazole": { name_ja: "ランソプラゾール", name_en: "Lansoprazole", category: "prodrug" },
  "struct-omeprazole": { name_ja: "オメプラゾール", name_en: "Omeprazole", category: "prodrug" },
  "struct-levodopa": { name_ja: "レボドパ", name_en: "Levodopa", category: "prodrug" },
  "struct-valacyclovir": { name_ja: "バラシクロビル", name_en: "Valacyclovir", category: "prodrug" },
  "struct-oseltamivir": { name_ja: "オセルタミビル", name_en: "Oseltamivir", category: "prodrug" },
  "struct-cefcapene-pivoxil": { name_ja: "セフカペンピボキシル", name_en: "Cefcapene pivoxil", category: "prodrug" },
  "struct-clopidogrel": { name_ja: "クロピドグレル", name_en: "Clopidogrel", category: "prodrug" },
  "struct-docarpamine": { name_ja: "ドカルパミン", name_en: "Docarpamine", category: "prodrug" },
  "struct-aflatoxin-b1": { name_ja: "アフラトキシンB1", name_en: "Aflatoxin B1", category: "carcinogen" },
  "struct-benzo-a-pyrene": { name_ja: "ベンゾ[a]ピレン", name_en: "Benzo[a]pyrene", category: "carcinogen" },
  "struct-ndma": { name_ja: "N-ニトロソジメチルアミン", name_en: "N-Nitrosodimethylamine", category: "carcinogen" },
  "struct-acrylamide": { name_ja: "アクリルアミド", name_en: "Acrylamide", category: "carcinogen" },
  "struct-o-toluidine": { name_ja: "o-トルイジン", name_en: "o-Toluidine", category: "carcinogen" },
  "struct-benzidine": { name_ja: "ベンジジン", name_en: "Benzidine", category: "carcinogen" },
  "struct-beta-naphthylamine": { name_ja: "β-ナフチルアミン", name_en: "beta-Naphthylamine", category: "carcinogen" },
  "struct-bcme": { name_ja: "ビス(クロロメチル)エーテル", name_en: "Bis(chloromethyl) ether", category: "carcinogen" },
  "struct-vinyl-chloride": { name_ja: "塩化ビニル", name_en: "Vinyl chloride", category: "carcinogen" },
  "struct-deoxynivalenol": { name_ja: "デオキシニバレノール", name_en: "Deoxynivalenol", category: "carcinogen" },
  "struct-tcdd": { name_ja: "2,3,7,8-TCDD", name_en: "2,3,7,8-TCDD", category: "carcinogen" },
  "struct-phenacetin": { name_ja: "フェナセチン", name_en: "Phenacetin", category: "carcinogen" },
  "struct-aspartame": { name_ja: "アスパルテーム", name_en: "Aspartame", category: "sweetener" },
  "struct-saccharin": { name_ja: "サッカリン", name_en: "Saccharin", category: "sweetener" },
  "struct-acesulfame-k": { name_ja: "アセスルファムカリウム", name_en: "Acesulfame potassium", category: "sweetener" },
  "struct-sucralose": { name_ja: "スクラロース", name_en: "Sucralose", category: "sweetener" },
  "struct-stevioside": { name_ja: "ステビオシド", name_en: "Stevioside", category: "sweetener" },
  "struct-glycyrrhizin": { name_ja: "グリチルリチン", name_en: "Glycyrrhizin", category: "sweetener" },
  "struct-sorbic-acid": { name_ja: "ソルビン酸", name_en: "Sorbic acid", category: "preservative" },
  "struct-benzoic-acid": { name_ja: "安息香酸", name_en: "Benzoic acid", category: "preservative" },
  "struct-dehydroacetic-acid": { name_ja: "デヒドロ酢酸", name_en: "Dehydroacetic acid", category: "preservative" },
  "struct-methylparaben": { name_ja: "パラオキシ安息香酸メチル", name_en: "Methylparaben", category: "preservative" },
  "struct-propionic-acid": { name_ja: "プロピオン酸", name_en: "Propionic acid", category: "preservative" },
  "struct-bha": { name_ja: "BHA", name_en: "BHA", category: "antioxidant" },
  "struct-bht": { name_ja: "BHT", name_en: "BHT", category: "antioxidant" },
  "struct-erythorbic-acid": { name_ja: "エリソルビン酸", name_en: "Erythorbic acid", category: "antioxidant" },
  "struct-propyl-gallate": { name_ja: "没食子酸プロピル", name_en: "Propyl gallate", category: "antioxidant" },
  "struct-opp": { name_ja: "OPP", name_en: "o-Phenylphenol", category: "antifungal" },
  "struct-tbz": { name_ja: "TBZ", name_en: "Thiabendazole", category: "antifungal" },
  "struct-imazalil": { name_ja: "イマザリル", name_en: "Imazalil", category: "antifungal" },
  "struct-diphenyl": { name_ja: "ジフェニル", name_en: "Biphenyl", category: "antifungal" },
  "struct-malathion": { name_ja: "マラチオン", name_en: "Malathion", category: "pesticide" },
  "struct-parathion": { name_ja: "パラチオン", name_en: "Parathion", category: "pesticide" },
  "struct-ddt": { name_ja: "DDT", name_en: "DDT", category: "pesticide" },
  "struct-glyphosate": { name_ja: "グリホサート", name_en: "Glyphosate", category: "pesticide" },
  "struct-paraquat": { name_ja: "パラコート", name_en: "Paraquat", category: "pesticide" },
  "struct-permethrin": { name_ja: "ペルメトリン", name_en: "Permethrin", category: "pesticide" },
  "struct-carbaryl": { name_ja: "カルバリル", name_en: "Carbaryl", category: "pesticide" },
  "struct-diazinon": { name_ja: "ダイアジノン", name_en: "Diazinon", category: "pesticide" },
  "struct-pcb": { name_ja: "PCB", name_en: "2,2',4,4',5,5'-Hexachlorobiphenyl", category: "endocrine_disruptor" },
  "struct-bisphenol-a": { name_ja: "ビスフェノールA", name_en: "Bisphenol A", category: "endocrine_disruptor" },
  "struct-dehp": { name_ja: "フタル酸ジ(2-エチルヘキシル)", name_en: "DEHP", category: "endocrine_disruptor" },
  "struct-nonylphenol": { name_ja: "ノニルフェノール", name_en: "Nonylphenol", category: "endocrine_disruptor" },
  "struct-tributyltin": { name_ja: "トリブチルスズ", name_en: "Tributyltin", category: "endocrine_disruptor" },
  "struct-pralidoxime": { name_ja: "プラリドキシム(PAM)", name_en: "Pralidoxime", category: "antidote" },
  "struct-atropine": { name_ja: "アトロピン", name_en: "Atropine", category: "antidote" },
  "struct-nac": { name_ja: "N-アセチルシステイン", name_en: "N-Acetylcysteine", category: "antidote" },
  "struct-dimercaprol": { name_ja: "ジメルカプロール(BAL)", name_en: "Dimercaprol", category: "antidote" },
  "struct-deferoxamine": { name_ja: "デフェロキサミン", name_en: "Deferoxamine", category: "antidote" },
  "struct-naloxone": { name_ja: "ナロキソン", name_en: "Naloxone", category: "antidote" },
  "struct-flumazenil": { name_ja: "フルマゼニル", name_en: "Flumazenil", category: "antidote" },
  "struct-methylene-blue": { name_ja: "メチレンブルー", name_en: "Methylene blue", category: "antidote" },
  "struct-epa": { name_ja: "EPA", name_en: "Eicosapentaenoic acid", category: "foshu" },
  "struct-dha": { name_ja: "DHA", name_en: "Docosahexaenoic acid", category: "foshu" },
  "struct-daidzein": { name_ja: "ダイゼイン", name_en: "Daidzein", category: "foshu" },
  "struct-egcg": { name_ja: "EGCG", name_en: "Epigallocatechin gallate", category: "foshu" },
  "struct-indigestible-dextrin": { name_ja: "難消化性デキストリン", name_en: "Indigestible dextrin", category: "foshu" },
  "struct-adrenaline": { name_ja: "アドレナリン", name_en: "Adrenaline", category: "pharmacology" },
  "struct-noradrenaline": { name_ja: "ノルアドレナリン", name_en: "Noradrenaline", category: "pharmacology" },
  "struct-dopamine": { name_ja: "ドパミン", name_en: "Dopamine", category: "pharmacology" },
  "struct-acetylcholine": { name_ja: "アセチルコリン", name_en: "Acetylcholine", category: "pharmacology" },
  "struct-indomethacin": { name_ja: "インドメタシン", name_en: "Indomethacin", category: "pharmacology" },
  "struct-diclofenac": { name_ja: "ジクロフェナク", name_en: "Diclofenac", category: "pharmacology" },
  "struct-cimetidine": { name_ja: "シメチジン", name_en: "Cimetidine", category: "pharmacology" },
  "struct-warfarin": { name_ja: "ワルファリン", name_en: "Warfarin", category: "pharmacology" },
  "struct-methamphetamine": { name_ja: "メタンフェタミン", name_en: "Methamphetamine", category: "pharmacology" },
  "struct-codeine": { name_ja: "コデイン", name_en: "Codeine", category: "pharmacology" },
  "struct-morphine": { name_ja: "モルヒネ", name_en: "Morphine", category: "pharmacology" },
  "struct-dexamethasone": { name_ja: "デキサメタゾン", name_en: "Dexamethasone", category: "pharmacology" },
}
