/**
 * generate-questions-catalog-seed.ts
 *
 * src/data/real-questions/exam-*.ts から問題IDを抽出し、
 * questions_catalog + product_catalog の INSERT SQL を生成する。
 *
 * 使い方:
 *   npx tsx scripts/generate-questions-catalog-seed.ts
 *
 * 出力:
 *   supabase/migrations/20260327_005_seed.sql
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, '..');
const QUESTIONS_DIR = path.join(PROJECT_ROOT, 'src', 'data', 'real-questions');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'supabase', 'migrations', '20260327_005_seed.sql');

// id: 'rNNN-NNN' パターン（シングルクォート・ダブルクォート両対応）
const ID_PATTERN = /["']id["']\s*:\s*["'](r(\d+)-(\d+))["']/g;

interface QuestionEntry {
  id: string;         // 例: 'r100-001'
  examRound: number;  // 例: 100
  seq: number;        // 例: 1
}

function extractQuestionIds(): QuestionEntry[] {
  const entries: QuestionEntry[] = [];
  const seenIds = new Set<string>();

  // exam-*.ts ファイルを取得してソート
  const files = fs.readdirSync(QUESTIONS_DIR)
    .filter(f => /^exam-\d+\.ts$/.test(f))
    .sort((a, b) => {
      const numA = parseInt(a.match(/\d+/)![0], 10);
      const numB = parseInt(b.match(/\d+/)![0], 10);
      return numA - numB;
    });

  for (const file of files) {
    const filePath = path.join(QUESTIONS_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');

    let match: RegExpExecArray | null;
    // lastIndex をリセット（gフラグ付きなので必要）
    ID_PATTERN.lastIndex = 0;

    while ((match = ID_PATTERN.exec(content)) !== null) {
      const id = match[1];
      const examRound = parseInt(match[2], 10);
      const seq = parseInt(match[3], 10);

      if (!seenIds.has(id)) {
        seenIds.add(id);
        entries.push({ id, examRound, seq });
      }
    }
  }

  // ID順にソート（回次 → 連番）
  entries.sort((a, b) => {
    if (a.examRound !== b.examRound) return a.examRound - b.examRound;
    return a.seq - b.seq;
  });

  return entries;
}

function generateSQL(entries: QuestionEntry[]): string {
  const lines: string[] = [];

  lines.push('-- 20260327_005_seed.sql');
  lines.push('-- シードデータ: product_catalog + questions_catalog');
  lines.push('-- Auto-generated by scripts/generate-questions-catalog-seed.ts');
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Total questions: ${entries.length}`);
  lines.push('');

  // Product catalog
  lines.push('-- =============================================================================');
  lines.push('-- Product catalog');
  lines.push('-- =============================================================================');
  lines.push('');
  lines.push("INSERT INTO product_catalog (id, name, billing_type, price_jpy, interval_months, granted_entitlements) VALUES");
  lines.push("  ('pro_monthly', 'Pro月額プラン', 'subscription', 980, 1,");
  lines.push("   ARRAY['notes_all', 'cards_all', 'analytics_full', 'cloud_sync']),");
  lines.push("  ('pro_annual',  'Pro年度パス',   'subscription', 7800, 12,");
  lines.push("   ARRAY['notes_all', 'cards_all', 'analytics_full', 'cloud_sync'])");
  lines.push('ON CONFLICT (id) DO NOTHING;');
  lines.push('');

  // Sentinel user comment
  lines.push('-- =============================================================================');
  lines.push('-- Sentinel user for billing_transactions anonymization');
  lines.push('-- =============================================================================');
  lines.push('-- NOTE: Create manually in Supabase Dashboard → Authentication → Users');
  lines.push('-- Email: deleted@system.local, UUID: 00000000-0000-0000-0000-000000000000');
  lines.push('--');
  lines.push('-- Supabase auth.users に直接 INSERT は RLS/トリガーの関係で推奨されない。');
  lines.push('-- Dashboard から手動作成後、以下を実行:');
  lines.push('--');
  lines.push("--   INSERT INTO users (id, status, role) VALUES");
  lines.push("--     ('00000000-0000-0000-0000-000000000000'::uuid, 'active', 'admin')");
  lines.push('--   ON CONFLICT (id) DO NOTHING;');
  lines.push('');

  // Questions catalog
  lines.push('-- =============================================================================');
  lines.push('-- Questions catalog (auto-generated)');
  lines.push('-- =============================================================================');
  lines.push('');
  lines.push("INSERT INTO questions_catalog (id, source_type, exam_round, seq, is_active) VALUES");

  const valueLines = entries.map((entry, index) => {
    const comma = index < entries.length - 1 ? ',' : '';
    return `  ('${entry.id}', 'past_exam', ${entry.examRound}, ${entry.seq}, true)${comma}`;
  });

  lines.push(...valueLines);
  lines.push('ON CONFLICT (id) DO NOTHING;');
  lines.push('');

  return lines.join('\n');
}

function main(): void {
  console.log('=== questions_catalog シード SQL 生成 ===\n');

  // 1. 問題IDを抽出
  console.log(`走査ディレクトリ: ${QUESTIONS_DIR}`);
  const entries = extractQuestionIds();

  if (entries.length === 0) {
    console.error('エラー: 問題IDが1件も見つかりませんでした。');
    process.exit(1);
  }

  // 2. 統計を表示
  const rounds = [...new Set(entries.map(e => e.examRound))].sort((a, b) => a - b);
  console.log(`\n抽出結果:`);
  console.log(`  問題ID数: ${entries.length}`);
  console.log(`  回次範囲: 第${rounds[0]}回 〜 第${rounds[rounds.length - 1]}回（${rounds.length}回分）`);
  console.log(`  回次別内訳:`);
  for (const round of rounds) {
    const count = entries.filter(e => e.examRound === round).length;
    console.log(`    第${round}回: ${count}問`);
  }

  // 3. SQL生成
  const sql = generateSQL(entries);

  // 4. 出力
  fs.writeFileSync(OUTPUT_FILE, sql, 'utf-8');
  const lineCount = sql.split('\n').length;
  console.log(`\n出力ファイル: ${OUTPUT_FILE}`);
  console.log(`SQLファイル行数: ${lineCount}行`);
  console.log('\n完了!');
}

main();
